# What is about ? 

Compute statistics several precompute solutions. 

Look on dependence on the beam size.

Solutions were obtained by CayleyPy-cube, with the following params: 


    
    hd1 256 
    hd2 128
    nrd 1
    batch size  100000
    lr  0.001
    Epochs 500 
    Kmax 26

In [226]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re
# import csv
import matplotlib.pyplot as plt
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

In [227]:
def get_solutions_stat(df_submit, source,IX_inf = 0):
    list_lens = []
    for k in range(len(df_submit)):
        sol = df_submit['path'].iloc[k]
        ln = len( sol.split('.'))
        list_lens.append(ln)
    l = np.array(list_lens[100:])
    mask = l < 90 # Higher length - unsolved 
    n_solved = mask.sum() 
    n_total = len(l)
    percent_solved = np.round(n_solved/n_total*100,1 )
    df_report = pd.DataFrame()
    IX = IX_inf
    #df_report.loc[IX,'source']= source
    df_report.loc[IX,'count (solved)']=  n_solved
    df_report.loc[IX,'count (total)']=  n_total
    if (n_solved>0):
        median_len = np.median( l[mask])
        mean_len = np.mean( l[mask])
        df_report.loc[IX,'min length (solved)']=  np.min( l[mask])
        df_report.loc[IX,'max length (solved)']=  np.max( l[mask]) 
        df_report.loc[IX,'std length (solved)']=  np.round( np.std( l[mask]) , 2)
        df_report.loc[IX,'percent (solved)']= percent_solved
        df_report.loc[IX,'median length (solved)']= median_len
        df_report.loc[IX,'mean length (solved)']= np.round(mean_len,1)
        df_report.loc[IX,'percentile10 length (solved)']= np.percentile( l[mask], 10 )
        df_report.loc[IX,'percentile90 length (solved)']= np.percentile( l[mask], 90 )
    else:
        median_len = -1
        mean_len = -1
        df_report.loc[IX,'min length (solved)']=  -1
        df_report.loc[IX,'max length (solved)']=  -1 
        df_report.loc[IX,'std length (solved)']=  -1
        df_report.loc[IX,'percent (solved)']= -1
        df_report.loc[IX,'median length (solved)']= -1
        df_report.loc[IX,'mean length (solved)']= -1
        df_report.loc[IX,'percentile10 length (solved)']= -1
        df_report.loc[IX,'percentile90 length (solved)']= -1
    #df_report.to_csv('df_report.csv')
    return df_report, n_solved
    

fn = '/kaggle/input/cayleypy-submissions/IhesCube_beam2p8_full/submission (48).csv'
df_submit = pd.read_csv(fn, index_col = 'initial_state_id')
display(df_submit.head(2))
df_report,n_solved = get_solutions_stat(df_submit,'submission (48).csv')
df_report

                                                               path
initial_state_id
0                 d2.-f2.-d1.r2.-d1.f0.d0.r0.f2.f2.r0.-f0.r0.-f1...
1                                       f1.d1.-f2.-d1.-f1.d1.f2.-d1

,count (solved),count (total),min length (solved),max length (solved),std length (solved),percent (solved),median length (solved),mean length (solved),percentile10 length (solved),percentile90 length (solved)
0,285.0,903.0,22.0,50.0,5.81,31.6,36.0,36.5,29.0,45.0

In [228]:
list_dirs = [
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p5_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p6_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p8_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p10_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p12_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p14_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p16_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_beam2p18_full',
    '/kaggle/input/cayleypy-submissions/IhesCube_full_submits'
            ]
df_report_full = pd.DataFrame()
for dirname in list_dirs:
    str_inf0 = dirname.split('_')[1]
    print(str_inf0)
    i_file = 0
    list_of_failed_names = ['']
    for dirpath, dirnames, filenames in os.walk(dirname):
        for filename in filenames:
            fullname = os.path.join(dirpath, filename)
            df = pd.read_csv(fullname,index_col ='initial_state_id')
            # display(df.head(1))    
            str_inf_full = str_inf0 + ' '+ str(i_file)
            i_file +=1
            df_report, n_solved = get_solutions_stat(df,filename,str_inf_full)    
            
            df_report.loc[str_inf_full,'Beam'] = str_inf0
            if len(df_report_full) == 0:
                df_report_full = df_report.copy()
            else:
                df_report_full = pd.concat([df_report_full, df_report], axis = 0)
            # display(df_report_full)
display(df_report_full)

beam2p5
beam2p6
beam2p8
beam2p10
beam2p12
beam2p14
beam2p16
beam2p18
full

,count (solved),count (total),min length (solved),max length (solved),std length (solved),percent (solved),median length (solved),mean length (solved),percentile10 length (solved),percentile90 length (solved),Beam
beam2p5 0,14.0,903.0,31.0,48.0,5.35,1.6,36.5,37.1,32.0,44.8,beam2p5
beam2p5 1,11.0,903.0,26.0,47.0,6.95,1.2,41.0,39.0,27.0,45.0,beam2p5
beam2p5 2,11.0,903.0,26.0,47.0,6.95,1.2,41.0,39.0,27.0,45.0,beam2p5
beam2p5 3,9.0,903.0,23.0,49.0,8.22,1.0,35.0,37.3,28.6,48.2,beam2p5
beam2p6 0,61.0,903.0,23.0,49.0,5.92,6.8,36.0,36.5,30.0,46.0,beam2p6
beam2p6 1,56.0,903.0,27.0,50.0,6.06,6.2,38.0,38.3,31.0,48.0,beam2p6
beam2p6 2,71.0,903.0,25.0,50.0,5.51,7.9,37.0,37.6,31.0,45.0,beam2p6
beam2p6 3,69.0,903.0,23.0,50.0,6.71,7.6,38.0,37.8,29.8,47.0,beam2p6
beam2p8 0,285.0,903.0,22.0,50.0,5.81,31.6,36.0,36.5,29.0,45.0,beam2p8
beam2p8 1,261.0,903.0,25.0,50.0,6.04,28.9,36.0,36.7,29.0,46.0,beam2p8
beam2p8 2,238.0,903.0,25.0,50.0,5.58,26.4,35.0,35.7,29.0,43.0,beam2p8
beam2p8 3,265.0,903.0,25.0,50.0,5.58,29.3,36.0,35.9,29.0,43.0,beam2p8
beam2p10 0,540.0,903.0,21.0,50.0,5.51,59.8,33.0,33.6,28.0,41.0,beam2p10
beam2p10 1,527.0,903.0,22.0,50.0,5.40,58.4,32.0,33.7,28.0,41.0,beam2p10
beam2p10 2,553.0,903.0,21.0,50.0,5.23,61.2,33.0,33.5,28.0,41.0,beam2p10
beam2p10 3,585.0,903.0,22.0,50.0,5.26,64.8,33.0,33.4,27.0,41.0,beam2p10
beam2p12 0,740.0,903.0,21.0,48.0,3.63,81.9,30.0,30.3,26.0,35.0,beam2p12
beam2p12 1,753.0,903.0,22.0,50.0,3.85,83.4,30.0,30.4,26.0,35.0,beam2p12
beam2p12 2,748.0,903.0,21.0,44.0,3.63,82.8,30.0,30.3,26.0,35.0,beam2p12
beam2p12 3,745.0,903.0,21.0,49.0,3.65,82.5,30.0,30.4,26.0,35.0,beam2p12
beam2p14 0,858.0,903.0,21.0,39.0,2.54,95.0,28.0,28.1,25.0,31.0,beam2p14
beam2p14 1,874.0,903.0,21.0,49.0,2.69,96.8,28.0,28.2,25.0,31.0,beam2p14
beam2p14 2,859.0,903.0,21.0,45.0,2.66,95.1,28.0,28.2,25.0,32.0,beam2p14
beam2p14 3,866.0,903.0,21.0,45.0,2.69,95.9,28.0,28.1,25.0,31.0,beam2p14
beam2p16 0,896.0,903.0,21.0,47.0,2.07,99.2,27.0,26.7,24.0,29.0,beam2p16
beam2p16 1,902.0,903.0,21.0,37.0,2.01,99.9,27.0,26.7,24.0,29.0,beam2p16
beam2p16 2,896.0,903.0,21.0,36.0,1.84,99.2,27.0,26.5,24.0,29.0,beam2p16
beam2p16 3,899.0,903.0,21.0,35.0,1.83,99.6,26.0,26.4,24.0,29.0,beam2p16
beam2p18 0,903.0,903.0,21.0,29.0,1.49,100.0,26.0,25.5,24.0,27.0,beam2p18
beam2p18 1,903.0,903.0,21.0,30.0,1.49,100.0,26.0,25.5,24.0,27.0,beam2p18
beam2p18 2,903.0,903.0,21.0,30.0,1.50,100.0,25.0,25.4,24.0,27.0,beam2p18
beam2p18 3,903.0,903.0,21.0,29.0,1.48,100.0,26.0,25.5,24.0,27.0,beam2p18
full 0,903.0,903.0,20.0,26.0,1.13,100.0,24.0,23.7,22.0,25.0,full
full 1,903.0,903.0,20.0,27.0,1.22,100.0,24.0,24.1,23.0,26.0,full
full 2,903.0,903.0,20.0,27.0,1.14,100.0,24.0,23.9,23.0,25.0,full
full 3,903.0,903.0,19.0,26.0,1.12,100.0,24.0,23.6,22.0,25.0,full
full 4,903.0,903.0,20.0,27.0,1.22,100.0,24.0,24.0,23.0,26.0,full
full 5,903.0,903.0,20.0,26.0,1.12,100.0,24.0,23.7,22.0,25.0,full

In [229]:
df_report_full.to_csv("df_report_full.csv")

In [230]:
df_report_aggregated = df_report_full.groupby('Beam').mean().round(1)
df_report_aggregated = df_report_aggregated.sort_values(
    "Beam",
    key=lambda s: s.str.extract(r'(\d+)$')[0].astype("Int64"),
    na_position="last",   # or "first"
)
df_report_aggregated.to_csv('df_report_aggregated.csv')
df_report_aggregated

,count (solved),count (total),min length (solved),max length (solved),std length (solved),percent (solved),median length (solved),mean length (solved),percentile10 length (solved),percentile90 length (solved)
Beam,,,,,,,,,,
beam2p5,11.2,903.0,26.5,47.8,6.9,1.2,38.4,38.1,28.6,45.8
beam2p6,64.2,903.0,24.5,49.8,6.0,7.1,37.2,37.6,30.4,46.5
beam2p8,262.2,903.0,24.2,50.0,5.8,29.0,35.8,36.2,29.0,44.2
beam2p10,551.2,903.0,21.5,50.0,5.4,61.0,32.8,33.6,27.8,41.0
beam2p12,746.5,903.0,21.2,47.8,3.7,82.6,30.0,30.4,26.0,35.0
beam2p14,864.2,903.0,21.0,44.5,2.6,95.7,28.0,28.2,25.0,31.2
beam2p16,898.2,903.0,21.0,38.8,1.9,99.5,26.8,26.6,24.0,29.0
beam2p18,903.0,903.0,21.0,29.5,1.5,100.0,25.8,25.5,24.0,27.0
full,903.0,903.0,19.8,26.5,1.2,100.0,24.0,23.8,22.5,25.3